# This is a basic workflow to help you get started with Actions

name: WDIO-CI

# Controls when the workflow will ru
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: ${{secrets.RUNNER}}
      LOG-LEVEL: ${{secrets.LOG_LEVEL}}
      TEST_NOPCommerce_ADMIN_USER: ${{secrets.TEST_NOPCommerce_ADMIN_USER}}
      TEST_NOPCommerce_ADMIN_PASSWORD: ${{secrets.TEST_NOPCommerce_ADMIN_PASSWORD}}
    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Running smoke test
        run: npm run test
